project:
  type: website
  preview: 
    port: 6543

website:
  title: "Deepak Ramani"
  description: "This is Deepak Ramani's personal blog."
  site-url: https://dr563105.github.io/  
  repo-url: https://github.com/dr563105/dr563105.github.io
  # favicon: favicon.jpg
  open-graph: true
  twitter-card:
    creator: "@thosegradients"
    card-style: summary_large_image
  navbar:
    background: "#eeeeee"
    right:
      - text: Blog
        href: blog.qmd
      # - icon: github
      #   href: https://github.com/
      # - icon: twitter
      #   href: https://twitter.com
      # - icon: rss
      #   href: blog.xml
      - text: Archive
        href: archive.qmd
  google-analytics: 
    tracking-id: "G-8HL173849C"
    anonymize-ip: true
  cookie-consent:
    type: express
    palette: light
  # reader-mode: true
  search: 
    location: navbar
    copy-button: true
 
format:
  html:
    theme: 
      light: ./_includes/ember.scss
      # dark: darkly
    css: ./_includes/styles.css
    code-link: true
    include-before-body: 
      ./_includes/analytics.html
    include-in-header: 
      ./_includes/google-ads.html

execute: 
  freeze: auto
