project:
  type: website
  preview: 
    port: 6542
  resources:
    - ads.txt

website:
  favicon: logo.png
  title: "Deepak Ramani's blog"
  description: "This is Deepak Ramani's personal blog."
  site-url: https://dr563105.github.io/  
  repo-url: https://github.com/dr563105/dr563105.github.io
  repo-actions: source
  repo-branch: master
  open-graph: true
  twitter-card:
    creator: "@thosegradients"
  page-navigation: true
  navbar:
    title: false
    left: 
      - text: Home
        href: index.qmd
      # - text: Projects
      #   href: projects/index.qmd
      #   menu:
      #     - text: MLOPS
      #       file: projects/mlops.qmd
      #     - text: Data Enginnering
      #       href: projects/data-engg.qmd
      - text: Notes
        href: notes/index.qmd
      # - text: Hobbies
      #   menu: 
      #     - text: Books/Audiobooks
      #       href: hobbies/books/cradle/index.qmd
      #     - text: Football
      #       href: hobbies/football/index.qmd
    right:
      - text: About
        href: about.qmd
      - text: Resume
        href: resume.pdf

  # sidebar: 
  #   - title: Notes
  #     pinned: true
  #     collapse-level: 1
  #     style: docked
  #     contents: notes/**

  google-analytics: 
    tracking-id: "G-V08NSV8XPF"
    anonymize-ip: true  
  cookie-consent:
    type: express
    palette: light
  search: 
    location: navbar
    copy-button: true
  page-footer: 
    left: Copyright 2024, Deepak Ramani |
          powered by [Quarto](https://quarto.org)
    right:
      - text: Archive
        href: archive.qmd
      - icon: rss
        href: index.xml
        
adsense:
  publisher-id: ca-pub-9028821857593432
  filters: 
    - adsense

format:
  html:
    theme: 
      light: [_includes/light-theme.scss]
      dark: [_includes/dark-theme.scss]
    highlight-style: dracula
    # css: _includes/styles.css
    # include-before-body: 
      # _includes/analytics.html
    # include-in-header: 
      # _includes/google-ads.html
    code-link: true
    smooth-scroll: true
    code-copy: hover

execute: 
  freeze: auto
